baseurl = "/"
title = "Watching from the Wall"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author]
  name = "Bradley Harr"
  bio = "Placeholder for bio blurb."
  avatar = "img/avatar.png"

[menu]
[[menu.main]]
  name = "Blog"
  pageRef = "/"
  weight = 1

[Params]
  description = "Watching from the Wall" # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = true # Show "Read more" button in list if true
  authorbox = true
  pager = true
  post_meta = ["date", "categories"] # Order of post meta information
  mainSections = ["post", "docs"]
  googleFontsLink = "https://fonts.googleapis.com/css2family=Newsreader:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,200;1,300;1,400;1,500;1,600;1,700;1,800&display=swap"

[Params.style.vars]
  highlightColor = "#e22d30" # Override highlight color

[Params.logo]
  title = "Watching from the Wall"
  subtitle = "Isaiah 62:6" # Logo subtitle

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["recent", "categories", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
  # Enable parts of social widget
  facebook = "username"
  twitter = "username"
  instagram = "username"
  telegram = "username"
  email = "bradley@bradleyharr.com"
